"""add archived_at to calls for dashboard archive/unarchive

Revision ID: 63d0c00c01e5
Revises: 35b1505c18db
Create Date: 2026-09-14 14:56:02.576667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63d0c00c01e5'
down_revision: Union[str, None] = '35b1505c18db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calls', schema=None) as batch_op:
        batch_op.add_column(sa.Column('archived_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calls', schema=None) as batch_op:
        batch_op.drop_column('archived_at')

    # ### end Alembic commands ###
