"""add editable message templates to business

Revision ID: 9306c91888a5
Revises: 398909741a7f
Create Date: 2026-08-17 16:51:09.471460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9306c91888a5'
down_revision: Union[str, None] = '398909741a7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('missed_call_message', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('review_request_message', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.drop_column('review_request_message')
        batch_op.drop_column('missed_call_message')

    # ### end Alembic commands ###
