"""add amd status callback correlation for missed-call detection

Revision ID: c859327d582c
Revises: 63d0c00c01e5
Create Date: 2026-09-14 15:34:25.323176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c859327d582c'
down_revision: Union[str, None] = '63d0c00c01e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pending_amd_results',
    sa.Column('dial_call_sid', sa.String(length=64), nullable=False),
    sa.Column('answered_by', sa.String(length=20), nullable=False),
    sa.Column('received_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('dial_call_sid')
    )
    with op.batch_alter_table('calls', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dial_call_sid', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_calls_dial_call_sid'), ['dial_call_sid'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calls', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_calls_dial_call_sid'))
        batch_op.drop_column('dial_call_sid')

    op.drop_table('pending_amd_results')
    # ### end Alembic commands ###
